#!/bin/bash

#echo "Running bash..."
cd src/
if [ ! -f "junk.tokens" ]; 
then
echo "Compiling Grammar file...";
java -cp antlr.jar org.antlr.v4.Tool junk.g4;
fi

if [ ! -f "Driver.class" ];
then
echo "Compiling Driver file...";
javac -cp .:antlr.jar Driver.java;
javac  Symbol.java;
javac  SymbolTable.java;
fi

#echo "hopefully file compiled successfully..."
#echo "running current java program"
java -cp .:antlr.jar Driver ../$1

